services:
  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000", "9001:9001"]
    volumes: [minio_data:/data]

  media-service:
    build: .
    ports: ["9096:9096"]
    env_file: .env.dev
    depends_on: [mongo, minio]
    restart: unless-stopped

volumes:
  mongo_data:
  minio_data:
