# src/main/resources/application-dev.yml (online)
# Activate with: SPRING_PROFILES_ACTIVE=dev

server:
  # Let the platform or env decide the port in online envs
  port: ${PORT:9096}

spring:
  application:
    name: media-service
  data:
    mongodb:
      # No localhost default here — force a proper online URI
      uri: ${SPRING_DATA_MONGODB_URI}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    oauth2:
      resourceserver:
        jwt:
          # Keep or replace with your IdP issuer if not Google
          issuer-uri: ${OAUTH2_ISSUER_URI:https://accounts.google.com}

logging:
  level:
    root: INFO
    com.tripwise.tripmedia: INFO

media:
  bucket: ${MEDIA_BUCKET}
  public-base-url: ${MEDIA_PUBLIC_BASE_URL}
  storage: s3

  s3:
    # Point to AWS S3 *or* your remote MinIO endpoint
    # e.g., https://s3.eu-central-1.amazonaws.com  OR  https://minio.my-domain.com
    endpoint: ${MEDIA_S3_ENDPOINT}
    region: ${MEDIA_S3_REGION:eu-central-1}
    access-key: ${MEDIA_S3_ACCESS_KEY}
    secret-key: ${MEDIA_S3_SECRET_KEY}
    # For AWS S3 generally false; for MinIO often true. Set via env.
    path-style-access: ${MEDIA_S3_PATH_STYLE_ACCESS:false}


journals:
  base-url: ${JOURNALS_BASE_URL}



