server:
  port: 9096

spring:
  application:
    name: media-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/mediadb}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

logging:
  level:
    root: INFO
    com.tripjournal.media: DEBUG

media:
  bucket: ${MEDIA_BUCKET:tripmedia}
  public-base-url: ${MEDIA_PUBLIC_BASE_URL:http://localhost:9096/media-files}
  s3:
    endpoint: ${MEDIA_S3_ENDPOINT:http://localhost:9000}   # MinIO
    region: ${MEDIA_S3_REGION:local}
    access-key: ${MEDIA_S3_ACCESS_KEY:minioadmin}
    secret-key: ${MEDIA_S3_SECRET_KEY:minioadmin}
    path-style-access: ${MEDIA_S3_PATH_STYLE_ACCESS:true}
